services:
  postgres:
    image: postgres:15
    container_name: restaurant-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shaunns1092
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    container_name: restaurant-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge